spring:
  datasource:
    url: jdbc:postgresql://ec2-54-157-4-216.compute-1.amazonaws.com:5432/d21n9ian5mvuvo
    username: ybdyemtdcirdmg
    password: 07049e5062437ffb330fe389b17048ca9135f0ef7e96dcd7783fe6ebb2f1e7bd
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: teste
      password: teste

server:
  port: 8080

biblioteca:
  app:
    jwtSecret: randomSecretKey
    jwtExpirationMs: 86400000